### ISSUE TITLE
HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by simpsonGO** [benedictus79/Hotm4rtei#21]
2024-02-20 20:08:13 - [0;31mERROR:[0m [vimeo] 360844858: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: Not Found>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U

Yes im in the latest version, with Python, ffmpeg and Hotm4rtei, 

ps: i dont know why but just two of my courses was found by this tool, the second one, has this issue and the other successfully download, thanks for that!

**Comment by benedictus79** [comment]
The 404 error is because the video possibly no longer exists. Can you view videos within the platform itself?

P.S.: The script can only find courses hosted on Hotmart itself; if they are on another platform, it will not be able to find them.

**Comment by simpsonGO** [comment]
ohh that explains why couldn't find the other courses, I tried to run it again and...

```

C:\Users\XXX\Desktop\Hotm4rtei-main\Hotm4rtei-main>pip install -r requirements.txt
Fatal error in launcher: Unable to create process using '"C:\Users\XXX\AppData\Local\Programs\Python\Python312\python.exe"  "C:\Users\XXX\AppData\Local\Programs\Python\Python312\Scripts\pip.exe" install -r requirements.txt': O sistema nÒo pode encontrar o arquivo especificado.


C:\Users\XXX\Desktop\Hotm4rtei-main\Hotm4rtei-main>python main.py
Could not find platform independent libraries <prefix>
Traceback (most recent call last):
  File "C:\Users\XXX\Desktop\Hotm4rtei-main\Hotm4rtei-main\main.py", line 3, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'

```

I already ran it in administrator mode and got the same error, don't waste your time, I don't need this course
