### ISSUE TITLE
Possible GUI for this project

### ISSUE THREAD

**Issue by doiiido** [benedictus79/Hotm4rtei#33]
Venho sugerir um acoplamento deste projeto com o [Katomart](https://github.com/katomaro/katomart/) para acelerar o desenvolvimento dos dois e adicionar neste a possiblidade de ter uma GUI para o usuário leigo.
O outro projeto está pendente ainda de um core plenamente funcional para download dos cursos, mas possui uma boa GUI e acreditos que o escopo de ambos se completam.

[Issue com a sugestão lá](https://github.com/katomaro/katomart/issues/23)

Atenciosamente,
Lincoln.

**Comment by doiiido** [comment]
No longer an option....

**Comment by benedictus79** [comment]
Este projeto Katomart é muito demorado e lento. Entretando, o hotmartei já tem um versão web.
