### ISSUE TITLE
Dont detect courses

### ISSUE THREAD

**Issue by voignar** [benedictus79/Hotm4rtei#47]
I have courses purchased on the hotmart platform but it does not detect the courses to be able to download them

![Captura de pantalla 2024-04-26 120108](https://github.com/benedictus79/Hotm4rtei/assets/2969205/c8c7f03a-da43-4466-a980-00a7a66205b4)
![Captura de pantalla 2024-04-26 120140](https://github.com/benedictus79/Hotm4rtei/assets/2969205/a4ce4058-b19a-4dbb-b830-fe7144b9e39b)

**Comment by benedictus79** [comment]
What is your version of Python? Is it possible to reinstall it to a newer version?

**Comment by voignar** [comment]
version: 3.11.4

**Comment by voignar** [comment]
Solved updating python
