### ISSUE TITLE
Falso positivo no google chrome

### ISSUE THREAD

**Issue by carvalhomourao** [benedictus79/Hotm4rtei#75]
Essa é a primeira issue que abro no github, então desculpe por algum equívoco. Eu baixei o arquivo executável do último release 2.2.1 e o chrome está impedindo o download por entender ser vírus, o que imagino seja um falso positivo. Não me recordo se isso chegou a ocorrer com o release anterior e se havia algum método de você contornar isso, mas deixo aqui o report.

**Comment by benedictus79** [comment]
Se o botão "Manter mesmo assim" não estiver aparecendo no Chrome, tente estas etapas:

Verifique as Configurações de Navegação Segura: Desative temporariamente a Navegação Segura nas configurações de "Privacidade e segurança" do Chrome.
Use o Gerenciador de Downloads: Pressione Ctrl + J para ver os downloads bloqueados e tente recuperar o arquivo.
Tente Outro Navegador: Use o Firefox ou Edge para fazer o download.

**Comment by carvalhomourao** [comment]
> Se o botão "Manter mesmo assim" não estiver aparecendo no Chrome, tente estas etapas:
> 
> Verifique as Configurações de Navegação Segura: Desative temporariamente a Navegação Segura nas configurações de "Privacidade e segurança" do Chrome. Use o Gerenciador de Downloads: Pressione Ctrl + J para ver os downloads bloqueados e tente recuperar o arquivo. Tente Outro Navegador: Use o Firefox ou Edge para fazer o download. Ou tente executar via python

Obrigado, acabei executando via python com sucesso. Obrigado pelo script, é muito útil para a gente ter armazenado o conteúdo que comprou.
